name: Arduino check
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: test
        run: |
          # Проверяем существование конфиг-файла
          ls
          if [ ! -f arduino/Bike/config.h ]; then
            echo "ERROR: config file not found!"
            exit 1
          fi  
          echo "Config file exist"
          g++ arduino/Bike/tests/testBTSerial.cpp \
          arduino/Bike/BTSerial.cpp \
          arduino/Bike/Parameters.cpp \
          arduino/Bike/mystring.cpp \
          arduino/Bike/config.cpp \
          -I include \
          include/Arduino.cpp \
          include/SoftwareSerial.cpp \
          -o testBTSerial
          ./testBTSerial
          rm testBTSerial